### ISSUE TITLE
tests/small/test_decompressor.py tests a

### ISSUE THREAD

**Issue by mwhudson** [ubuntu/ubuntu-make#459]
As of 229e4ee8dbb5557935eb7c4a7ed490c6c5267512:

```
ubuntu@artful:~/ubuntu-make$ python3.6 `which nosetests3` tests/small/test_decompressor.py 
...........FFFF
======================================================================
FAIL: We decompress a valid zip file successfully
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/ubuntu-make/tests/small/test_decompressor.py", line 130, in test_decompress_zip
    self.assertIsNone(results[fd].error)
AssertionError: "'str' object has no attribute 'external_attr'" is not None
-------------------- >> begin captured logging << --------------------
umake.decompressor: INFO: Requesting decompression to /tmp/tmplv6a5hle
umake.decompressor: DEBUG: Extracting to /tmp/tmplv6a5hle
umake.decompressor: DEBUG: zip file
umake.decompressor: ERROR: A decompression to /tmp/tmplv6a5hle failed: 'str' object has no attribute 'external_attr'
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/ubuntu-make/umake/decompressor.py", line 105, in _decompress
    archive.extractall(tempdest)
  File "/usr/lib/python3.6/zipfile.py", line 1501, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/ubuntu/ubuntu-make/umake/decompressor.py", line 47, in _extract_member
    mode = member.external_attr >> 16 & 0x1FF
AttributeError: 'str' object has no attribute 'external_attr'
umake.decompressor: INFO: Decompression to /tmp/tmplv6a5hle finished
umake.decompressor: INFO: All pending decompression done to ['/tmp/tmplv6a5hle'] done.
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: We decompress a valid zip file successfully
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/ubuntu-make/tests/small/test_decompressor.py", line 49, in tearDown
    super().tearDown()
  File "/home/ubuntu/ubuntu-make/tests/tools/__init__.py", line 64, in tearDown
    self.assertEqual(self.error_warn_logs.getvalue(), "")
AssertionError: 'A decompression to /tmp/tmplv6a5hle faile[639 chars]\'\n' != ''
Diff is 688 characters long. Set self.maxDiff to None to see it.
-------------------- >> begin captured logging << --------------------
umake.decompressor: INFO: Requesting decompression to /tmp/tmplv6a5hle
umake.decompressor: DEBUG: Extracting to /tmp/tmplv6a5hle
umake.decompressor: DEBUG: zip file
umake.decompressor: ERROR: A decompression to /tmp/tmplv6a5hle failed: 'str' object has no attribute 'external_attr'
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/ubuntu-make/umake/decompressor.py", line 105, in _decompress
    archive.extractall(tempdest)
  File "/usr/lib/python3.6/zipfile.py", line 1501, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/ubuntu/ubuntu-make/umake/decompressor.py", line 47, in _extract_member
    mode = member.external_attr >> 16 & 0x1FF
AttributeError: 'str' object has no attribute 'external_attr'
umake.decompressor: INFO: Decompression to /tmp/tmplv6a5hle finished
umake.decompressor: INFO: All pending decompression done to ['/tmp/tmplv6a5hle'] done.
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: We decompress a valid zip file successfully, retaining the right permissions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/ubuntu-make/tests/small/test_decompressor.py", line 146, in test_decompress_zip_good_permission
    self.assertIsNone(results[fd].error)
AssertionError: "'str' object has no attribute 'external_attr'" is not None
-------------------- >> begin captured logging << --------------------
umake.decompressor: INFO: Requesting decompression to /tmp/tmpfvayqs1_
umake.decompressor: DEBUG: Extracting to /tmp/tmpfvayqs1_
umake.decompressor: DEBUG: zip file
umake.decompressor: ERROR: A decompression to /tmp/tmpfvayqs1_ failed: 'str' object has no attribute 'external_attr'
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/ubuntu-make/umake/decompressor.py", line 105, in _decompress
    archive.extractall(tempdest)
  File "/usr/lib/python3.6/zipfile.py", line 1501, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/ubuntu/ubuntu-make/umake/decompressor.py", line 47, in _extract_member
    mode = member.external_attr >> 16 & 0x1FF
AttributeError: 'str' object has no attribute 'external_attr'
umake.decompressor: INFO: Decompression to /tmp/tmpfvayqs1_ finished
umake.decompressor: INFO: All pending decompression done to ['/tmp/tmpfvayqs1_'] done.
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: We decompress a valid zip file successfully, retaining the right permissions
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/ubuntu-make/tests/small/test_decompressor.py", line 49, in tearDown
    super().tearDown()
  File "/home/ubuntu/ubuntu-make/tests/tools/__init__.py", line 64, in tearDown
    self.assertEqual(self.error_warn_logs.getvalue(), "")
AssertionError: 'A decompression to /tmp/tmpfvayqs1_ faile[639 chars]\'\n' != ''
Diff is 688 characters long. Set self.maxDiff to None to see it.
-------------------- >> begin captured logging << --------------------
umake.decompressor: INFO: Requesting decompression to /tmp/tmpfvayqs1_
umake.decompressor: DEBUG: Extracting to /tmp/tmpfvayqs1_
umake.decompressor: DEBUG: zip file
umake.decompressor: ERROR: A decompression to /tmp/tmpfvayqs1_ failed: 'str' object has no attribute 'external_attr'
Traceback (most recent call last):
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ubuntu/ubuntu-make/umake/decompressor.py", line 105, in _decompress
    archive.extractall(tempdest)
  File "/usr/lib/python3.6/zipfile.py", line 1501, in extractall
    self._extract_member(zipinfo, path, pwd)
  File "/home/ubuntu/ubuntu-make/umake/decompressor.py", line 47, in _extract_member
    mode = member.external_attr >> 16 & 0x1FF
AttributeError: 'str' object has no attribute 'external_attr'
umake.decompressor: INFO: Decompression to /tmp/tmpfvayqs1_ finished
umake.decompressor: INFO: All pending decompression done to ['/tmp/tmpfvayqs1_'] done.
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 13 tests in 4.083s

FAILED (failures=4)
```

**Comment by LyzardKing** [comment]
Why are you running the test like that?
Try running it like it's supposed to, "./runtests tests/small/test_decompressor.py"
You need the configuration from runtests

**Comment by LyzardKing** [comment]
@mwhudson Did you get the test to run properly?

**Comment by mwhudson** [comment]
I was trying to reproduce the failure seen when rebuilding the package in Ubuntu with python3.6 as the default: https://launchpad.net/~canonical-foundations/+archive/ubuntu/python3.6-as-default/+build/12745043 -- so it's possible I'm doing something wrong but there is a real problem here!

**Comment by LyzardKing** [comment]
As far as I can tell the issue is with the patch used to fix the permissions in the zipfile (https://bugs.python.org/issue15795).
Could it be that this does not work in python 3.6 for some reason?

**Comment by LyzardKing** [comment]
It might not be what we want to do, but this seems to work..
The test works, I haven't looked at anything else.
I think something weird happened with the zipfile library...
https://github.com/LyzardKing/ubuntu-make/commit/f3622de773c85a88137dfadf0c406ddac0ec9aea

@didrocks , any idea?

**Comment by didrocks** [comment]
it happened to just be a flaky test IIRC, I saw it once but couldn't investigate more. Do you have it reliably?

**Comment by LyzardKing** [comment]
To be honest I'm not sure,
I tried to frankenstein a python3.6 default system...
on that the test failed every time, saying that 
'str' object has no attribute 'external_attr'

if I change to the zipinfo it works...
But again, I'm not sure, I was just trying something, to get it to run on python 3.6

**Comment by didrocks** [comment]
I didn't try on 3.6 yet, it's not impossible that things changed there.

**Comment by LyzardKing** [comment]
Yes, that's the issue here, python 3.6.
https://lists.ubuntu.com/archives/ubuntu-devel/2017-June/039826.html
