### ISSUE TITLE
umake -v ide eclipse-jee

### ISSUE THREAD

**Issue by davidjimenezanca** [ubuntu/ubuntu-make#393]
I cant not install eclipse ide in Lubuntu 16.10:

ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 140, in get_sha_and_start_download
    res = download_result[self.sha512_url]
KeyError: 'https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/neon/1a/eclipse-jee-neon-1a-linux-gtk-x86_64.tar.gz.sha512&r=1'

**Comment by didrocks** [comment]
Hey! Thanks for using ubuntu make.
Which version of Ubuntu Make did you use? I think your issue is fixed in the official ubuntu make ppa: *ppa:ubuntu-desktop/ubuntu-make*.

Try to upgrade to that version and then installing eclipse again.

**Comment by davidjimenezanca** [comment]
Ni idea

Enviado desde Yahoo Mail con Android 
 
  El mar. 3 3e ene. 3e 2017 a las 8:47, Didier Roche<notifications@github.com> escribió:   
Hey! Thanks for using ubuntu make.
Which version of Ubuntu Make did you use? I think your issue is fixed in the official ubuntu make ppa: ppa:ubuntu-desktop/ubuntu-make.

Try to upgrade to that version and then installing eclipse again.

**Comment by leschekfm** [comment]
I had the same issue while installing visual-studio-code. Upgrading from 16.02.1 to 16.11.1~xenial1 resolved the issue for me.

**Comment by LyzardKing** [comment]
It works on my system.
There have been new releases, so closing for now.
Reopen if this problem persists

**Comment by adalvigi** [comment]
Doesn't work on my machine (Ubuntu 16.04). Please fix this as I'm unable to install Eclipse both from the snap and from the ppa versions.

The error I get is:
```
ERROR: https://www.eclipse.org//downloads/download.php?file=/technology/epp/downloads/release/photon/R/eclipse-java-photon-R-linux-gtk-x86_64.tar.gz.sha512&r=1 couldn't finish download: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check',))
ERROR: Unhandled exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/umake/tools.py", line 158, in wrapper
    function(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/umake/frameworks/ide.py", line 128, in get_sha_and_start_download
    sha512 = res.buffer.getvalue().decode('utf-8').split()[0]
AttributeError: 'NoneType' object has no attribute 'getvalue'
```

**Comment by LyzardKing** [comment]
Don't comment on old issues to report a new one.
It's harder to keep track of open issues if closed ones have comments years after being fixed.
In this case the error message is different anyway...
